apiVersion: apps/v1
kind: Deployment
metadata:
  name: permutation-service
  labels:
    app: permutation-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: permutation-service
  template:
    metadata:
      labels:
        app: permutation-service
    spec:
      containers:
      - name: permutation-service
        image: ghcr.io/torba2207/permutation-service:latest
        imagePullPolicy: Always
        env:
        - name: AiService__BaseUrl
          value: "http://ai-service/"
        ports:
        - containerPort: 5001
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"