version: '3.8'

services:
  ai-service:
    build:
      context: ./ServiceMeshTestApplication/AiService
      dockerfile: Dockerfile
    container_name: ai-service-host
    network_mode: "host"  # <--- THIS IS THE KEY
    environment:
      - TARGET_MODEL=llama3.2
    volumes:
      - ./ServiceMeshTestApplication/AiService/data/ollama_engine:/app/data/ollama_engine
      - ./ServiceMeshTestApplication/AiService/data/ollama_models:/root/.ollama
      - ./ServiceMeshTestApplication/AiService/data/img:/app/data/img
    restart: always