[control_plane]
node1 ansible_host=10.29.20.101

[workers]
node4 ansible_host=10.29.20.111
node5 ansible_host=10.29.20.112
node6 ansible_host=10.29.20.113

[ai_vms]
ai ansible_host=10.29.20.120

[load_generator]
lg ansible_host=10.29.20.130

[all:vars]
ansible_user=root
ansible_ssh_private_key_file="{{ lookup('community.general.dotenv', '.env', key='SSH_PRIVATE_KEY') }}"