---
- name: Deploy Istio Environment (Hybrid)
  hosts: localhost
  gather_facts: false
  vars:
    test_ns: thesis-test
    app_dir: ../k8s/
    istio_dir: ../istio
  tasks:
    - name: Ensure istio-system namespace exists
      kubernetes.core.k8s:
        name: istio-system
        api_version: v1
        kind: Namespace
        state: present

    - name: Install Istio Control Plane (Imperative CLI)
      ansible.builtin.command: istioctl install --set profile=default -y

    - name: Ensure thesis namespace exists with Istio injection label
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ test_ns }}"
            labels:
              istio-injection: enabled

    - name: Apply Istio App Deployments and configs
      kubernetes.core.k8s:
        state: present
        namespace: "{{ test_ns }}"
        src: "{{ item }}"
      loop:
        - "{{ app_dir }}/permutation-service/permutation-service-istio-deployment.yaml"
        - "{{ app_dir }}/permutation-service/permutation-service-istio-service.yaml"
        - "{{ istio_dir }}/istio-main-gateway.yaml"
        - "{{ app_dir }}/permutation-service/permutation-virtual-service-istio.yaml"
        - "{{ app_dir }}/integration-service/integration-service-istio-deployment.yaml"
        - "{{ app_dir }}/integration-service/integration-service-istio-service.yaml"
        - "{{ app_dir }}/integration-service/integration-virtual-service-istio.yaml"
        - "{{ app_dir }}/fibonacci-service/fibonacci-service-istio-deployment.yaml"
        - "{{ app_dir }}/fibonacci-service/fibonacci-service-istio-service.yaml"
        - "{{ app_dir }}/fibonacci-service/fibonacci-virtual-service-istio.yaml"
        - "{{ app_dir }}/differential-equations-service/differential-equations-service-istio-deployment.yaml"
        - "{{ app_dir }}/differential-equations-service/differential-equations-service-istio-service.yaml"
        - "{{ app_dir }}/differential-equations-service/differential-equations-virtual-service-istio.yaml"
        - "{{ app_dir }}/digital-filters-service/digital-filters-service-istio-deployment.yaml"
        - "{{ app_dir }}/digital-filters-service/digital-filters-service-istio-service.yaml"
        - "{{ app_dir }}/digital-filters-service/digital-filters-virtual-service-istio.yaml"
        - "{{ app_dir }}/video-service/video-service-istio-deployment.yaml"
        - "{{ app_dir }}/video-service/video-service-istio-service.yaml"
        - "{{ app_dir }}/video-service/video-virtual-service-istio.yaml"
        - "{{ app_dir }}/ai-service/ai-service-external.yaml"
        - "{{ app_dir }}/ai-service/ai-virtual-service-istio.yaml"