apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: video-vs
spec:
  hosts:
  - "*"
  gateways:
  - main-gateway
  http:
  - match:
    - uri:
        prefix: /api/video
    route:
    - destination:
        host: video-service
        port:
          number: 80