apiVersion: v1
kind: Service
metadata:
  name: video-service
  labels:
    app: video-service
spec:
  type: NodePort
  selector:
    app: video-service
  ports:
    - name: http
      port: 80
      targetPort: 5006
      nodePort: 30006
      protocol: TCP